# Generated by Django 4.0.2 on 2022-02-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_remove_order_item_remove_order_name_remove_order_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.AddField(
            model_name='order',
            name='destination_lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='destination_long',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='merchants.item'),
        ),
    ]
