# Generated by Django 4.0.2 on 2022-02-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_remove_order_destination_order_destination_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Processing'), ('2', 'on Route'), ('3', 'Delivered')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
