# Generated by Django 4.0.2 on 2022-02-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_storemerchant_storedriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedriver',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
