# Generated by Django 4.0.2 on 2022-03-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_storemerchant_name_merchant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='merchant',
            new_name='user',
        ),
    ]
